(function () {
  const content = document.getElementById('content'), detailDialog = document.getElementById('detailDialog'), formDialog = document.getElementById('formDialog')
  const groups = [
    ['工作台', [['dashboard', '运营工作台', '⌂']]],
    ['内容中心', [['questions', '题库管理', '题'], ['collection', '内容采集', '采'], ['knowledge', '知识点管理', '知'], ['readings', '政治阅读内容', '阅']]],
    ['学习运营', [['plan', '今日计划', '计'], ['records', '学习记录', '录'], ['abilities', '能力画像', '能'], ['problems', '学习问题', '问'], ['diagnoses', '错因诊断', '因']]],
    ['考试运营', [['mock-papers', '模考试卷', '卷'], ['mock-records', '模考记录', '考'], ['mock-analysis', '考试分析', '析']]],
    ['系统', [['ai', 'AI 配置', 'AI'], ['sources', '内容源配置', '源'], ['system', '系统状态', '态']]]
  ]
  const pages = {
    dashboard: ['运营工作台', '掌握内容供给、学习闭环和系统健康状态'], questions: ['题库管理', '统一管理行测与申论题目，识别库存和质量风险'], collection: ['内容采集', '管理来源、上传、审核与采集运行结果'], knowledge: ['知识点管理', '从知识体系查看题量覆盖与低库存风险'], readings: ['政治阅读内容', '管理政治阅读素材、结构化状态与发布质量'], plan: ['今日计划', '查看真实用户计划、任务来源与执行进度'], records: ['学习记录', '追溯行测、申论、政治阅读和模考学习行为'], abilities: ['能力画像', '查看能力建立度、样本可信度与薄弱方向'], problems: ['学习问题', '跟踪问题证据、优先级、状态与主要根因'], diagnoses: ['错因诊断', '查看规则与 AI 诊断证据及用户确认结果'], 'mock-papers': ['模考试卷', '管理行测与申论模考试卷及题目覆盖'], 'mock-records': ['模考记录', '查看用户模考完成与评分情况'], 'mock-analysis': ['考试分析', '比较模考表现、模块表现与能力校准状态'], ai: ['AI 配置', '维护模型配置并查看真实连接状态'], sources: ['内容源配置', '管理内容来源、启停状态与最近运行结果'], system: ['系统状态', '集中查看接口、内容、学习闭环与 AI 健康状态']
  }
  const state = { view: 'dashboard', tab: '', inventory: null }

  const esc = value => String(value === null || value === undefined ? '' : value).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]))
  const fmt = value => value ? String(value).replace('T', ' ').slice(0, 19) : '—'
  const listOf = data => Array.isArray(data) ? data : ((data && (data.list || data.records || data.items)) || [])
  const badge = (value, kind = 'status') => '<span class="badge ' + Display.tone(value) + '">' + esc(Display.text(kind, value)) + '</span>'
  const empty = text => '<div class="empty">' + esc(text || '暂无真实数据') + '</div>'
  const card = (title, body, extra = '') => '<section class="card ' + extra + '"><div class="card-head"><h2>' + esc(title) + '</h2></div>' + body + '</section>'
  const kpi = (label, value, note, cls = 'accent-blue') => '<div class="card kpi ' + cls + '"><div class="kpi-label">' + esc(label) + '</div><div class="kpi-value">' + esc(value) + '</div><div class="kpi-note">' + esc(note || '') + '</div></div>'
  const json = value => { try { return typeof value === 'string' ? JSON.parse(value) : value } catch (_) { return null } }
  const table = (headers, rows) => rows.length ? '<div class="card table-wrap"><table><thead><tr>' + headers.map(x => '<th>' + esc(x) + '</th>').join('') + '</tr></thead><tbody>' + rows.join('') + '</tbody></table></div>' : empty()
  const tabs = items => '<div class="tabs">' + items.map(([id, label]) => '<button class="tab ' + (state.tab === id ? 'active' : '') + '" data-tab="' + id + '">' + label + '</button>').join('') + '</div>'

  window.AdminApp = {
    setBusy(busy) { const el = document.getElementById('status'); el.textContent = busy ? '正在读取真实数据…' : '数据已同步'; el.classList.toggle('busy', busy) },
    showError(message) { document.getElementById('status').textContent = '请求失败'; if (!content.querySelector('.error-state')) content.insertAdjacentHTML('afterbegin', '<div class="error-state">' + esc(message) + '<br><button class="button small" data-retry>重试</button></div>') }
  }

  function buildNavigation() {
    document.getElementById('navigation').innerHTML = groups.map(([name, items]) => '<div class="nav-group"><div class="nav-group-title">' + name + '</div>' + items.map(([id, label, icon]) => '<button class="nav-item" data-view="' + id + '"><span class="nav-icon">' + icon + '</span>' + label + '</button>').join('') + '</div>').join('')
    document.querySelectorAll('[data-view]').forEach(button => button.onclick = () => navigate(button.dataset.view))
  }
  function navigate(view, tab) { state.view = pages[view] ? view : 'dashboard'; state.tab = tab || ''; location.hash = state.view + (state.tab ? ':' + state.tab : ''); render() }
  function setHeader() {
    const page = pages[state.view]; document.getElementById('pageTitle').textContent = page[0]; document.getElementById('pageDescription').textContent = page[1]
    const group = groups.find(g => g[1].some(i => i[0] === state.view)); document.getElementById('breadcrumb').textContent = group[0] + ' / ' + page[0]
    document.querySelectorAll('.nav-item').forEach(x => x.classList.toggle('active', x.dataset.view === state.view)); document.getElementById('currentUser').textContent = Api.context.userId
  }
  function bindTabs() { content.querySelectorAll('[data-tab]').forEach(x => x.onclick = () => navigate(state.view, x.dataset.tab)) }
  async function load(path) { return Api.request(path) }
  async function inventory() { if (!state.inventory) state.inventory = await load('/api/admin/content/inventory'); return state.inventory }

  async function renderDashboard() {
    const [inv, sources, logs, plan, answers, overview, problems, providers, papers] = await Promise.all([inventory(), load('/api/admin/content/sources'), load('/api/admin/content/crawl-logs'), load('/api/plan/today'), load('/api/practice/answers?page=1&size=100'), load('/api/abilities/overview'), load('/api/learning-problems'), load('/api/admin/ai-providers'), load('/api/admin/mock-papers')])
    const o = inv.overview || {}, answerList = listOf(answers), problemList = listOf(problems), sourceList = listOf(sources), logList = listOf(logs), providerList = listOf(providers)
    const low = (inv.modules || []).flatMap(m => (m.knowledgePoints || []).filter(k => k.lowStock).map(k => ({ module: m.moduleName, name: k.name, count: k.trainable })))
    const failed = logList.filter(x => x.status === 'FAILED'), aiOk = providerList.some(x => x.enabled && x.lastTestStatus === 'SUCCESS'), activeSources = sourceList.filter(x => x.enabled).length
    const actions = []
    if (o.needsReviewCount) actions.push(['待审核内容', o.needsReviewCount + ' 条采集结果等待处理', 'collection:exceptions'])
    if (low.length) actions.push(['知识点低库存', low.length + ' 个知识点训练题不足', 'knowledge'])
    if (failed.length) actions.push(['采集失败', failed.length + ' 次运行需要排查', 'collection:logs'])
    if (!listOf(papers).length) actions.push(['模考试卷为空', '需要配置至少一套可用试卷', 'mock-papers'])
    const health = [['后端接口', true, '核心接口已响应'], ['内容供给', o.trainableTotal > 0, o.trainableTotal + ' 道可训练题'], ['内容采集', activeSources > 0 && !failed.length, activeSources + ' 个启用来源，' + failed.length + ' 次失败'], ['学习闭环', answerList.length > 0 && overview.totalCount > 0, answerList.length + ' 条作答，' + problemList.length + ' 个学习问题'], ['AI 服务', aiOk, aiOk ? '存在可用 Provider' : '未发现可用 Provider']]
    content.innerHTML = '<div class="grid kpi-grid">' + kpi('可训练题', o.trainableTotal || 0, '进入日常训练的真实库存') + kpi('待审核内容', o.needsReviewCount || 0, '采集异常与低置信内容', 'accent-warn') + kpi('能力建立度', (overview.evaluatedCount || 0) + '/' + (overview.totalCount || 0), '另有 ' + (overview.assessingCount || 0) + ' 项摸底中', 'accent-teal') + kpi('当前学习问题', problemList.filter(x => x.status !== 'RESOLVED').length, '持续跟踪，不按单题抖动', 'accent-red') + kpi('今日计划', plan ? plan.plannedMinutes + ' 分钟' : '未生成', plan ? Display.text('status', plan.status) : '无计划') + '</div>' +
      '<div class="grid two-col" style="margin-top:16px">' + card('今日待处理', actions.length ? '<div class="list">' + actions.map(a => '<div class="list-item action-item"><div><b>' + esc(a[0]) + '</b><div class="muted">' + esc(a[1]) + '</div></div><button class="link" data-jump="' + a[2] + '">立即处理 →</button></div>').join('') + '</div>' : '<div class="notice success">目前没有高优先级运营事项。</div>') + card('系统健康', health.map(x => '<div class="health-row"><b>' + x[0] + '</b><span class="muted">' + esc(x[2]) + '</span>' + badge(x[1] ? 'SUCCESS' : 'FAILED') + '</div>').join('')) + '</div>' +
      '<div class="grid two-col" style="margin-top:16px">' + card('题库库存', '<div class="grid three-col">' + (inv.modules || []).map(m => '<div class="card module-card" data-module="' + esc(m.code) + '"><div class="muted">' + esc(m.moduleName) + '</div><div class="module-value">' + m.trainable + '</div><div class="kpi-note">总量 ' + m.totalQuestions + ' · 未使用 ' + m.unused + '</div></div>').join('') + '</div>') + card('最近学习动态', answerList.slice(0, 6).map(a => '<div class="list-item"><div><b>题目 #' + a.questionId + '</b><div class="muted">' + Display.text('practice', a.practiceType) + ' · ' + fmt(a.answerTime) + '</div></div>' + badge(a.correct ? 'SUCCESS' : 'FAILED') + '</div>').join('') || empty()) + '</div>'
    content.querySelectorAll('[data-jump]').forEach(x => x.onclick = () => { const [v, t] = x.dataset.jump.split(':'); navigate(v, t) }); content.querySelectorAll('[data-module]').forEach(x => x.onclick = () => { sessionStorage.setItem('admin.question.module', x.dataset.module); navigate('questions') })
  }

  async function renderQuestions() {
    const inv = await inventory(), module = sessionStorage.getItem('admin.question.module') || '', query = new URLSearchParams({ page: '1', size: '60' }); if (module) query.set('knowledgePointCode', module)
    const [questions, essays] = await Promise.all([load('/api/questions?' + query), load('/api/admin/essay-questions?page=1&size=30')]); const qs = listOf(questions), es = listOf(essays)
    content.innerHTML = '<div class="page-actions"><button class="button" data-import>导入题目</button><button class="button primary" data-collection>进入内容采集</button></div><div class="grid kpi-grid">' + (inv.modules || []).map(m => kpi(m.moduleName, m.trainable, '总量 ' + m.totalQuestions + ' · 未使用 ' + m.unused, m.code === module ? 'accent-teal' : 'accent-blue')).join('') + '</div>' +
      '<form class="filters" id="questionFilters"><div class="field"><label>模块</label><select name="module"><option value="">全部模块</option>' + (inv.modules || []).map(m => '<option value="' + m.code + '" ' + (m.code === module ? 'selected' : '') + '>' + m.moduleName + '</option>').join('') + '</select></div><div class="field"><label>状态</label><select name="status"><option value="">全部状态</option><option>ACTIVE</option><option>DRAFT</option><option>SUSPENDED</option><option>ARCHIVED</option></select></div><button class="button primary">筛选</button></form>' +
      card('行测题目 · 当前页 ' + qs.length + ' 条', tableRowsQuestions(qs)) + '<div style="height:16px"></div>' + card('申论题目 · ' + es.length + ' 条', tableRowsEssays(es))
    document.querySelector('[data-import]').onclick = showImport; document.querySelector('[data-collection]').onclick = () => navigate('collection'); document.getElementById('questionFilters').onsubmit = e => { e.preventDefault(); sessionStorage.setItem('admin.question.module', new FormData(e.target).get('module')); renderQuestions() }
    bindQuestionDetails(); bindEssayDetails()
  }
  function tableRowsQuestions(items) { return table(['ID', '题目摘要', '题型', '难度', '用途', '来源', '状态', '版本', '操作'], items.map(q => '<tr><td>#' + q.id + '</td><td><b>' + esc((q.stem || '').slice(0, 54)) + '</b></td><td>' + Display.text('type', q.questionType) + '</td><td>' + (q.difficulty || '—') + '</td><td>' + badge(q.usageType, 'usage') + '</td><td>' + esc(q.source || Display.text('source', q.sourceType)) + '</td><td>' + badge(q.status) + '</td><td>v' + q.version + '</td><td><button class="link" data-question="' + q.id + '">查看</button></td></tr>')) }
  function tableRowsEssays(items) { return table(['ID', '题目', '题型', '字数', '分值', '状态', '操作'], items.map(q => '<tr><td>#' + q.id + '</td><td><b>' + esc((q.title || q.prompt || '').slice(0, 58)) + '</b></td><td>' + esc(q.questionType || '申论') + '</td><td>' + (q.wordLimit || '—') + '</td><td>' + (q.totalScore || '—') + '</td><td>' + badge(q.status) + '</td><td><button class="link" data-essay="' + q.id + '">查看</button></td></tr>')) }
  function bindQuestionDetails() { content.querySelectorAll('[data-question]').forEach(x => x.onclick = async () => showQuestion(await load('/api/admin/questions/' + x.dataset.question))) }
  function bindEssayDetails() { content.querySelectorAll('[data-essay]').forEach(x => x.onclick = async () => showObject('申论题目详情', await load('/api/admin/essay-questions/' + x.dataset.essay))) }
  function showQuestion(q) { const options = q.options || []; document.getElementById('detailContent').innerHTML = '<h2>题目 #' + q.id + '</h2><div class="chips">' + badge(q.status) + badge(q.usageType, 'usage') + '<span class="badge info">v' + q.version + '</span></div><h3>题干</h3><p>' + esc(q.stem) + '</p><div class="list">' + options.map(o => '<div class="list-item"><b>' + esc(o.optionKey) + '</b><span>' + esc(o.content) + '</span></div>').join('') + '</div><h3>正确答案</h3><div class="notice success">' + esc(q.correctAnswer) + '</div><h3>解析</h3><p>' + esc(q.analysis || '暂无解析') + '</p><dl class="detail-grid"><dt>知识点</dt><dd>' + esc((q.knowledgePoints || []).map(k => k.name).join(' / ') || '—') + '</dd><dt>来源</dt><dd>' + esc(q.source || '—') + '</dd><dt>参考耗时</dt><dd>' + (q.standardTimeSeconds || '—') + ' 秒</dd></dl>'; detailDialog.showModal() }
  function showImport() { document.getElementById('formContent').innerHTML = '<h2>CSV 批量导入</h2><p class="muted">单行失败不会影响其他题目，导入结果将逐行反馈。</p><form id="importForm"><div class="field"><label>选择 CSV 文件</label><input name="file" type="file" accept=".csv" required></div><br><button class="button primary">开始导入</button></form><div id="importResult"></div>'; formDialog.showModal(); document.getElementById('importForm').onsubmit = async e => { e.preventDefault(); const data = await loadWith('/api/questions/import', { method: 'POST', body: new FormData(e.target), timeout: 120000 }); document.getElementById('importResult').innerHTML = '<div class="notice success">总计 ' + data.total + '，成功 ' + data.successCount + '，失败 ' + data.failureCount + '</div>' + (data.failures || []).map(x => '<div class="notice warning">第 ' + x.row + ' 行：' + esc(x.reason) + '</div>').join('') } }
  const loadWith = (path, opts) => Api.request(path, opts)

  async function renderCollection() {
    state.tab = state.tab || 'overview'; const [inv, sources, logs] = await Promise.all([inventory(), load('/api/admin/content/sources'), load('/api/admin/content/crawl-logs')]); let body = ''
    if (state.tab === 'overview') body = '<div class="grid kpi-grid">' + kpi('自动入库', inv.overview.trainableTotal, '当前可训练库存') + kpi('待人工审核', inv.overview.needsReviewCount, '低置信或异常内容', 'accent-warn') + kpi('采集失败', inv.overview.crawlFailedCount, '当前失败队列', 'accent-red') + kpi('内容来源', listOf(sources).length, '已登记来源', 'accent-teal') + '</div>' + card('模块供给结构', (inv.modules || []).map(m => '<div class="health-row"><b>' + m.moduleName + '</b><div><div class="metric-bar"><span style="width:' + Math.min(100, m.trainable / Math.max(1, inv.overview.trainableTotal) * 400) + '%"></span></div><small class="muted">未使用 ' + m.unused + '</small></div><strong>' + m.trainable + '</strong></div>').join(''))
    if (state.tab === 'sources') body = sourcesTable(listOf(sources), true)
    if (state.tab === 'upload') body = '<div class="card"><h2>文件上传采集</h2><p class="muted">仅使用真实文件；上传后执行解析、去重和质量检查。</p><form id="uploadForm"><div class="field"><label>CSV 文件</label><input type="file" name="file" accept=".csv" required></div><br><button class="button primary">上传并处理</button></form><div id="uploadResult"></div></div>'
    if (state.tab === 'exceptions') { const staging = await load('/api/admin/content/staging?status=NEEDS_REVIEW&page=1'); body = stagingTable(listOf(staging)) }
    if (state.tab === 'logs') body = logsTable(listOf(logs))
    content.innerHTML = tabs([['overview', '采集概览'], ['sources', '采集来源'], ['upload', '文件上传'], ['exceptions', '异常处理'], ['logs', '采集日志']]) + body; bindTabs(); bindCollectionActions()
  }
  function sourcesTable(items, action) { return table(['来源', '类型', '状态', '地址 / 说明', '最近运行', '操作'], items.map(s => '<tr><td><b>' + esc(s.name) + '</b><div class="muted">#' + s.id + '</div></td><td>' + esc(s.sourceTypeText || s.sourceType || '—') + '</td><td>' + badge(s.enabled ? 'ACTIVE' : 'SUSPENDED') + '</td><td>' + esc(s.baseUrl || s.description || '—') + '</td><td>' + fmt(s.lastCrawlTime) + '</td><td>' + (action ? '<button class="button small primary" data-crawl="' + s.id + '">执行采集</button>' : '<button class="link" data-source-log="' + s.id + '">查看日志</button>') + '</td></tr>')) }
  function logsTable(items) { return table(['时间', '来源', '结果', '发现', '解析', '入库', '重复', '异常', '失败', '说明'], items.map(x => '<tr><td>' + fmt(x.createTime || x.startTime) + '</td><td>' + esc(x.sourceName || ('#' + (x.sourceId || '—'))) + '</td><td>' + badge(x.status) + '</td><td>' + (x.discovered || 0) + '</td><td>' + (x.parsed || 0) + '</td><td>' + (x.imported || 0) + '</td><td>' + (x.duplicates || 0) + '</td><td>' + (x.needsReview || 0) + '</td><td>' + (x.failed || 0) + '</td><td>' + esc(x.message || '—') + '</td></tr>')) }
  function stagingTable(items) { return table(['ID', '标题 / 题干', '来源', '问题', '状态', '操作'], items.map(x => '<tr><td>#' + x.id + '</td><td>' + esc((x.title || x.stem || x.rawContent || '').slice(0, 60)) + '</td><td>' + esc(x.sourceName || x.source || '—') + '</td><td>' + esc(x.reviewReason || x.errorMessage || '待人工判断') + '</td><td>' + badge(x.status) + '</td><td><button class="link" data-staging="' + x.id + '">查看证据</button></td></tr>')) }
  function bindCollectionActions() {
    content.querySelectorAll('[data-crawl]').forEach(x => x.onclick = async () => { x.disabled = true; const result = await loadWith('/api/admin/content/sources/' + x.dataset.crawl + '/crawl', { method: 'POST', timeout: 120000 }); alert('采集任务已执行：' + (result.message || '请查看采集日志')); state.inventory = null; navigate('collection', 'logs') })
    const upload = document.getElementById('uploadForm'); if (upload) upload.onsubmit = async e => { e.preventDefault(); const result = await loadWith('/api/admin/content/upload', { method: 'POST', body: new FormData(e.target), timeout: 120000 }); document.getElementById('uploadResult').innerHTML = '<div class="notice success">共 ' + result.total + ' 条，入库 ' + result.imported + '，重复 ' + result.duplicates + '，待审核 ' + result.needsReview + '，失败 ' + result.failed + '</div>' }
    content.querySelectorAll('[data-staging]').forEach(x => x.onclick = async () => showObject('异常内容证据', await load('/api/admin/content/staging/' + x.dataset.staging)))
  }

  async function renderKnowledge() { const [points, inv] = await Promise.all([load('/api/knowledge-points'), inventory()]); const modules = inv.modules || []; const selected = Number(sessionStorage.getItem('admin.knowledge.id') || (modules[0] && modules[0].id)); const module = modules.find(x => x.id === selected) || modules[0]; const all = listOf(points); content.innerHTML = '<div class="grid two-col"><section class="card"><h2>知识体系</h2><ul class="tree">' + modules.map(m => '<li class="' + (module && m.id === module.id ? 'active' : '') + '" data-knowledge="' + m.id + '"><b>' + esc(m.moduleName) + '</b><span class="muted"> · ' + m.trainable + ' 题</span></li>' + (m.knowledgePoints || []).map(k => '<li style="padding-left:28px" data-knowledge="' + m.id + '">' + esc(k.name) + ' <span class="badge ' + (k.lowStock ? 'warning' : 'positive') + '">' + k.trainable + '</span></li>').join('')).join('') + '</ul></section><section class="card"><h2>' + esc(module ? module.moduleName : '知识点详情') + '</h2>' + (module ? '<div class="grid three-col">' + kpi('题目总量', module.totalQuestions, '含各状态') + kpi('可训练', module.trainable, '当前有效库存', 'accent-teal') + kpi('未使用', module.unused, '尚未进入作答', 'accent-warn') + '</div><h3>子知识点覆盖</h3>' + ((module.knowledgePoints || []).map(k => '<div class="health-row"><b>' + esc(k.name) + '</b><span class="muted">' + (k.lowStock ? '库存不足，需要补充' : '库存正常') + '</span><strong>' + k.trainable + '</strong></div>').join('') || '<div class="notice">当前题目仅关联模块级知识点，暂无更细粒度覆盖统计。</div>') + '<button class="button primary" data-go-questions>查看关联题目</button>' : empty()) + '</section></div><div class="card" style="margin-top:16px"><h2>基础配置</h2>' + table(['编码', '名称', '层级', '父级', '重要度', '提升潜力', '迁移价值'], all.map(p => '<tr><td>' + esc(p.code) + '</td><td><b>' + esc(p.name) + '</b></td><td>' + (p.level || '—') + '</td><td>' + (p.parentId || '—') + '</td><td>' + (p.importance || '—') + '</td><td>' + (p.improvementPotential || '—') + '</td><td>' + (p.transferValue || '—') + '</td></tr>')) + '</div>'; content.querySelectorAll('[data-knowledge]').forEach(x => x.onclick = () => { sessionStorage.setItem('admin.knowledge.id', x.dataset.knowledge); renderKnowledge() }); const go = content.querySelector('[data-go-questions]'); if (go) go.onclick = () => { sessionStorage.setItem('admin.question.module', module.code); navigate('questions') } }

  async function renderReadings() { const [topics, data] = await Promise.all([load('/api/admin/reading-topics'), load('/api/admin/reading-materials?page=1&size=100')]); const items = listOf(data), topicList = listOf(topics); content.innerHTML = '<div class="grid kpi-grid">' + kpi('素材总量', data.total || items.length, '真实政治阅读内容') + kpi('已发布', items.filter(x => x.status === 'ACTIVE').length, '可供用户阅读', 'accent-teal') + kpi('草稿', items.filter(x => x.status === 'DRAFT').length, '待结构化或审核', 'accent-warn') + kpi('主题数', topicList.length, '内容分类') + '</div><div style="height:16px"></div>' + table(['ID', '标题', '主题', '来源', '发布日期', 'AI 状态', '发布状态', '操作'], items.slice(0, 100).map(x => '<tr><td>#' + x.id + '</td><td><b>' + esc(x.title) + '</b></td><td>' + esc(x.topicName || '未分类') + '</td><td>' + esc(x.source || '—') + '</td><td>' + esc(x.publishDate || '—') + '</td><td>' + badge(x.aiStatus || 'PENDING', 'aiStatus') + '</td><td>' + badge(x.status) + '</td><td><button class="link" data-reading="' + x.id + '">查看</button></td></tr>')); content.querySelectorAll('[data-reading]').forEach(x => x.onclick = async () => showObject('政治阅读内容详情', await load('/api/admin/reading-materials/' + x.dataset.reading))) }

  async function renderPlan() { const plan = await load('/api/plan/today'); if (!plan) { content.innerHTML = empty('当前用户尚未生成今日计划'); return } const items = plan.items || []; content.innerHTML = '<div class="grid kpi-grid">' + kpi('计划时长', plan.plannedMinutes + ' 分钟', '实际 ' + (plan.actualMinutes || 0) + ' 分钟') + kpi('任务数', items.length, '保持当天计划稳定') + kpi('已完成题目', items.reduce((s, x) => s + (x.completedQuestionCount || 0), 0), '来自真实答题记录', 'accent-teal') + kpi('计划状态', Display.text('status', plan.status), plan.planDate, 'accent-warn') + '</div><div style="height:16px"></div>' + card('生成原因', '<div class="notice">' + esc(plan.generationReason) + '</div>') + '<div style="height:16px"></div>' + table(['顺序', '任务', '目的', '来源问题', '时长', '题量进度', '状态', '安排原因'], items.map(x => '<tr><td>' + x.sortNo + '</td><td><b>' + esc(x.knowledgePointName) + '</b><div class="muted">' + Display.text('itemType', x.itemType) + '</div></td><td>' + badge(x.purpose, 'purpose') + '</td><td>' + Display.text('problem', x.problemType) + '</td><td>' + x.plannedMinutes + ' 分钟</td><td>' + x.completedQuestionCount + '/' + x.targetQuestionCount + '</td><td>' + badge(x.status) + '</td><td>' + esc(x.reason) + '</td></tr>')) }

  async function renderRecords() { state.tab = state.tab || 'answers'; let body = ''
    if (state.tab === 'answers') { const data = await load('/api/practice/answers?page=1&size=100'); const items = listOf(data); body = table(['时间', '题目', '结果', '用户答案', '答案快照', '耗时', '场景', '信心', '错因', '操作'], items.map(a => '<tr><td>' + fmt(a.answerTime) + '</td><td>#' + a.questionId + '</td><td>' + badge(a.correct ? 'SUCCESS' : 'FAILED') + '</td><td>' + esc(a.userAnswer) + '</td><td>' + esc(a.correctAnswerSnapshot) + '</td><td>' + Math.round(a.durationMs / 1000) + ' 秒</td><td>' + Display.text('practice', a.practiceType) + '</td><td>' + Display.text('confidence', a.confidenceType) + '</td><td>' + Display.text('error', a.errorType) + '</td><td><button class="link" data-answer="' + a.id + '" data-question="' + a.questionId + '">查看链路</button></td></tr>')) }
    if (state.tab === 'essay') { const data = await load('/api/admin/essay-answers?page=1&size=100'); body = genericRecords(listOf(data), '申论作答') }
    if (state.tab === 'reading') { const data = await load('/api/admin/reading-materials?page=1&size=100'); const items = listOf(data).filter(x => x.readStatus); body = genericRecords(items, '政治阅读记录') }
    if (state.tab === 'mock') { const data = await load('/api/mock/history'); body = mockHistoryTable(listOf(data)) }
    content.innerHTML = tabs([['answers', '行测答题'], ['essay', '申论作答'], ['reading', '政治阅读'], ['mock', '模考记录']]) + body; bindTabs(); content.querySelectorAll('[data-answer]').forEach(x => x.onclick = () => showLearningTrace(x.dataset.answer, x.dataset.question)); if (new URLSearchParams(location.search).get('openAnswer') === '1') { const first = content.querySelector('[data-answer]'); if (first) await showLearningTrace(first.dataset.answer, first.dataset.question) } }
  async function showLearningTrace(answerId, questionId) {
    const [answers, question, diagnoses, abilities, problems, plan] = await Promise.all([load('/api/practice/answers?page=1&size=200'), load('/api/admin/questions/' + questionId), load('/api/error-diagnoses?limit=200'), load('/api/abilities/overview'), load('/api/learning-problems'), load('/api/plan/today')])
    const answer = listOf(answers).find(x => String(x.id) === String(answerId)); const knowledge = json(answer && answer.knowledgeSnapshot) || []; const ids = knowledge.map(x => x.id)
    document.getElementById('detailContent').innerHTML = '<h2>单题学习详情</h2><div class="timeline"><div class="timeline-item"><b>题目与作答</b><p>' + esc(question.stem) + '</p><div class="chips">' + badge(answer && answer.correct ? 'SUCCESS' : 'FAILED') + '<span class="badge info">用户答案 ' + esc(answer && answer.userAnswer) + '</span><span class="badge">答案快照 ' + esc(answer && answer.correctAnswerSnapshot) + '</span><span class="badge">' + Math.round((answer && answer.durationMs || 0) / 1000) + ' 秒</span></div></div><div class="timeline-item"><b>错因诊断</b><p>' + esc(listOf(diagnoses).filter(d => String(d.answerRecordId) === String(answerId)).map(d => d.suspectedCause + '（' + d.confidence + '%）').join('；') || '本题未产生错因诊断') + '</p></div><div class="timeline-item"><b>能力画像</b><p>' + esc((abilities.abilities || []).filter(a => ids.includes(a.knowledgePointId)).map(a => a.knowledgePointName + '：' + Display.text('abilityStatus', a.status) + '，样本 ' + a.sampleCount).join('；') || '暂无对应能力') + '</p></div><div class="timeline-item"><b>学习问题</b><p>' + esc(listOf(problems).filter(p => ids.includes(p.knowledgePointId)).map(p => p.title + '（' + Display.text('problemStatus', p.status) + '）').join('；') || '未形成学习问题') + '</p></div><div class="timeline-item"><b>今日计划影响</b><p>' + esc((plan.items || []).filter(i => ids.includes(i.knowledgePointId)).map(i => i.knowledgePointName + '：' + i.reason).join('；') || '未进入当前今日计划；能力和问题变化将在下次生成计划时生效') + '</p></div></div>'; detailDialog.showModal()
  }
  function genericRecords(items, label) { return items.length ? table(['ID', label, '状态', '时间', '详情'], items.map(x => '<tr><td>#' + x.id + '</td><td><b>' + esc(x.title || x.questionTitle || x.materialTitle || ('记录 #' + x.id)) + '</b></td><td>' + badge(x.status || x.aiStatus || 'COMPLETED') + '</td><td>' + fmt(x.answerTime || x.createTime || x.updateTime) + '</td><td><button class="link" data-object="' + encodeURIComponent(JSON.stringify(x)) + '">查看</button></td></tr>')) : empty('暂无' + label) }

  async function renderAbilities() { const data = await load('/api/abilities/overview'), items = data.abilities || []; content.innerHTML = '<div class="grid kpi-grid">' + kpi('完整评估', data.evaluatedCount + '/' + data.totalCount, '达到可靠样本标准') + kpi('摸底中', data.assessingCount, '分数仅作过程观察', 'accent-warn') + kpi('覆盖率', data.coveragePercent + '%', '不将未测评显示为低分', 'accent-teal') + '</div><div style="height:16px"></div>' + table(['考试板块', '能力', '状态', '掌握', '速度', '稳定', '可信度', '样本', '趋势', '最近练习'], items.map(a => '<tr><td>' + (a.examSection === 'XINGCE' ? '行测' : '申论') + '</td><td><b>' + esc(a.knowledgePointName) + '</b></td><td>' + badge(a.status, 'abilityStatus') + '</td><td>' + (a.status === 'UNASSESSED' ? '未测评' : a.masteryScore) + '</td><td>' + (a.status === 'UNASSESSED' ? '—' : a.speedScore) + '</td><td>' + (a.status === 'UNASSESSED' ? '—' : a.stabilityScore) + '</td><td>' + (a.status === 'UNASSESSED' ? '—' : a.confidenceScore) + '</td><td>' + a.sampleCount + '</td><td>' + (a.masteryTrend == null ? '—' : (a.masteryTrend > 0 ? '↑ ' : '↓ ') + Math.abs(a.masteryTrend)) + '</td><td>' + fmt(a.lastPracticeTime) + '</td></tr>')) }
  async function renderProblems() { const items = listOf(await load('/api/learning-problems')); content.innerHTML = '<div class="grid kpi-grid">' + kpi('未解决', items.filter(x => x.status !== 'RESOLVED').length, '持续跟踪问题') + kpi('观察中', items.filter(x => x.status === 'OBSERVING').length, '证据不足不直接确认', 'accent-warn') + kpi('验证中', items.filter(x => x.status === 'VERIFYING').length, '优先进入验证任务', 'accent-teal') + kpi('已解决', items.filter(x => x.status === 'RESOLVED').length, '后续恶化可重新打开') + '</div><div style="height:16px"></div>' + table(['问题', '类型', '状态', '严重度', '优先级', '主要根因', '证据', '发现时间'], items.map(x => '<tr><td><b>' + esc(x.title) + '</b><div class="muted">' + esc(x.knowledgePointName) + '</div></td><td>' + Display.text('problem', x.problemType) + '</td><td>' + badge(x.status, 'problemStatus') + '</td><td>' + x.severity + '</td><td><b>' + x.priorityScore + '</b></td><td>' + esc(x.rootCause || '待诊断') + '</td><td><button class="link" data-evidence="' + encodeURIComponent(x.evidenceJson || '{}') + '">查看证据</button></td><td>' + fmt(x.discoveredTime) + '</td></tr>')); content.querySelectorAll('[data-evidence]').forEach(x => x.onclick = () => showObject('学习问题证据', json(decodeURIComponent(x.dataset.evidence)))) }
  async function renderDiagnoses() { const items = listOf(await load('/api/error-diagnoses?limit=200')); content.innerHTML = '<div class="grid kpi-grid">' + kpi('诊断总数', items.length, '按知识点与候选根因去重') + kpi('待确认', items.filter(x => x.status === 'PENDING_CONFIRMATION').length, '证据不足不直接认定', 'accent-warn') + kpi('用户确认', items.filter(x => x.confirmedByUser === true).length, '反馈已进入诊断事实', 'accent-teal') + kpi('用户否认', items.filter(x => x.confirmedByUser === false).length, '保留但不作为主根因') + '</div><div style="height:16px"></div>' + table(['更新时间', '题目 / 记录', '候选根因', '置信度', '出现次数', '规则状态', 'AI 分析', '用户反馈', '证据'], items.map(x => '<tr><td>' + fmt(x.updateTime) + '</td><td>题 #' + x.questionId + '<div class="muted">记录 #' + x.answerRecordId + '</div></td><td><b>' + esc(x.suspectedCause) + '</b></td><td>' + x.confidence + '%</td><td>' + x.occurrenceCount + '</td><td>' + badge(x.status) + '</td><td>' + esc(x.aiExplanation || '未生成') + '<div class="muted">' + Display.text('aiStatus', x.aiStatus) + '</div></td><td>' + (x.confirmedByUser == null ? '待用户确认' : x.confirmedByUser ? '确认' : '否认') + '</td><td><button class="link" data-diagnosis="' + encodeURIComponent(x.evidenceJson || '{}') + '">查看</button></td></tr>')); content.querySelectorAll('[data-diagnosis]').forEach(x => x.onclick = () => showObject('错因诊断证据', json(decodeURIComponent(x.dataset.diagnosis)))) }

  async function renderMockPapers() { const items = listOf(await load('/api/admin/mock-papers')); content.innerHTML = '<div class="grid kpi-grid">' + kpi('试卷总数', items.length, '行测与申论') + kpi('已启用', items.filter(x => x.status === 'ACTIVE').length, '可进入考试', 'accent-teal') + kpi('行测试卷', items.filter(x => x.examType === 'XINGCE').length, '客观题') + kpi('申论试卷', items.filter(x => x.examType === 'SHENLUN').length, '主观题') + '</div><div style="height:16px"></div>' + table(['ID', '试卷', '类型', '年度', '时长', '总分', '题目区块', '状态', '操作'], items.map(x => '<tr><td>#' + x.id + '</td><td><b>' + esc(x.name) + '</b><div class="muted">' + esc(x.source || '—') + '</div></td><td>' + (x.examType === 'XINGCE' ? '行测' : '申论') + '</td><td>' + (x.sourceYear || '—') + '</td><td>' + x.durationMinutes + ' 分钟</td><td>' + x.totalScore + '</td><td>' + (x.sections || []).length + '</td><td>' + badge(x.status) + '</td><td><button class="link" data-paper="' + x.id + '">查看详情</button></td></tr>')); content.querySelectorAll('[data-paper]').forEach(x => x.onclick = async () => showObject('模考试卷详情', await load('/api/admin/mock-papers/' + x.dataset.paper))) }
  function mockHistoryTable(items) { return items.length ? table(['考试时间', '试卷', '状态', '得分', '耗时', '正确率', '操作'], items.map(x => '<tr><td>' + fmt(x.submitTime || x.startTime || x.createTime) + '</td><td>' + esc(x.paperName || ('试卷 #' + x.paperId)) + '</td><td>' + badge(x.status) + '</td><td>' + (x.totalScore || x.score || '—') + '</td><td>' + (x.durationSeconds ? Math.round(x.durationSeconds / 60) + ' 分钟' : '—') + '</td><td>' + (x.correctRate == null ? '—' : x.correctRate + '%') + '</td><td><button class="link" data-object="' + encodeURIComponent(JSON.stringify(x)) + '">查看</button></td></tr>')) : empty('当前用户暂无模考记录') }
  async function renderMockRecords() { content.innerHTML = mockHistoryTable(listOf(await load('/api/mock/history'))); bindObjects() }
  async function renderMockAnalysis() { const [history, perf, abilities] = await Promise.all([load('/api/mock/history'), load('/api/mock/performance'), load('/api/abilities/overview')]); const hs = listOf(history), ps = listOf(perf); content.innerHTML = '<div class="grid kpi-grid">' + kpi('模考次数', hs.length, '真实提交记录') + kpi('考试能力校准', hs.length ? '已有样本' : '待模考', '不以练习题替代考试数据', 'accent-warn') + kpi('已评估能力', abilities.evaluatedCount + '/' + abilities.totalCount, '能力画像建立度', 'accent-teal') + '</div><div style="height:16px"></div>' + card('模块表现', ps.length ? table(['模块', '题量', '正确率', '得分', '能力校准'], ps.map(x => '<tr><td>' + esc(x.moduleName || x.knowledgePointName || '—') + '</td><td>' + (x.questionCount || x.sampleCount || '—') + '</td><td>' + (x.correctRate || '—') + '</td><td>' + (x.score || '—') + '</td><td>' + esc(x.calibrationStatus || '已有真实样本') + '</td></tr>')) : empty('完成模考后展示模块表现、得分变化与能力校准结果')) }

  async function renderAi() { const items = listOf(await load('/api/admin/ai-providers')); content.innerHTML = '<div class="notice">密钥仅显示脱敏值，不在页面回显真实内容。AI 只负责解释和生成，不直接修改能力、问题或计划。</div>' + table(['服务商', '模型', '启用', '默认', '密钥', '最近测试', '延迟', '测试时间', '操作'], items.map(x => '<tr><td><b>' + esc(x.name || x.code) + '</b><div class="muted">' + esc(x.code) + '</div></td><td>' + esc(x.effectiveModel || x.model || '—') + '</td><td>' + badge(x.enabled ? 'ACTIVE' : 'SUSPENDED') + '</td><td>' + (x.defaultProvider ? '<span class="badge info">默认</span>' : '—') + '</td><td>' + esc(x.maskedKey || '未配置') + '</td><td>' + badge(x.lastTestStatus || (x.configured ? 'CONFIGURED' : 'UNCONFIGURED'), 'aiStatus') + '<div class="muted">' + esc(x.lastTestMessage || '') + '</div></td><td>' + (x.lastTestLatencyMs || '—') + ' ms</td><td>' + fmt(x.lastTestTime) + '</td><td><button class="button small" data-ai="' + esc(x.code) + '">测试连接</button></td></tr>')); content.querySelectorAll('[data-ai]').forEach(x => x.onclick = async () => { const result = await loadWith('/api/admin/ai-providers/' + x.dataset.ai + '/test', { method: 'POST', body: {} }); alert(result.message || '连接测试完成'); renderAi() }) }
  async function renderSources() { const [sources, logs] = await Promise.all([load('/api/admin/content/sources'), load('/api/admin/content/crawl-logs')]); content.innerHTML = sourcesTable(listOf(sources), false); content.querySelectorAll('[data-source-log]').forEach(x => x.onclick = () => { sessionStorage.setItem('admin.source.id', x.dataset.sourceLog); navigate('collection', 'logs') }) }
  async function renderSystem() { const checks = await Promise.allSettled([load('/api/admin/content/inventory'), load('/api/abilities/overview'), load('/api/learning-problems'), load('/api/admin/ai-providers'), load('/api/admin/content/crawl-logs')]); const labels = ['内容库存接口', '能力画像接口', '学习问题接口', 'AI 配置接口', '采集日志接口']; const logs = checks[4].status === 'fulfilled' ? listOf(checks[4].value) : []; content.innerHTML = '<div class="grid kpi-grid">' + kpi('接口可用', checks.filter(x => x.status === 'fulfilled').length + '/' + checks.length, '管理控台关键读取接口') + kpi('采集失败', logs.filter(x => x.status === 'FAILED').length, '最近日志中的失败运行', 'accent-red') + kpi('最近采集', logs.length ? fmt(logs[0].createTime || logs[0].startTime) : '无记录', '真实运行日志', 'accent-teal') + '</div><div style="height:16px"></div>' + card('关键服务检查', checks.map((x, i) => '<div class="health-row"><b>' + labels[i] + '</b><span class="muted">' + (x.status === 'fulfilled' ? '请求成功并返回业务数据' : esc(x.reason.message)) + '</span>' + badge(x.status === 'fulfilled' ? 'SUCCESS' : 'FAILED') + '</div>').join('')) + '<div style="height:16px"></div>' + card('最近异常', logs.filter(x => x.status === 'FAILED').length ? logsTable(logs.filter(x => x.status === 'FAILED').slice(0, 20)) : '<div class="notice success">最近采集日志没有失败记录。应用尚未提供持久化接口异常日志查询，因此不会虚构“系统无异常”。</div>') }

  function showObject(title, object) { document.getElementById('detailContent').innerHTML = '<h2>' + esc(title) + '</h2><div class="code">' + esc(JSON.stringify(object, null, 2)) + '</div>'; detailDialog.showModal() }
  function bindObjects() { content.querySelectorAll('[data-object]').forEach(x => x.onclick = () => showObject('记录详情', JSON.parse(decodeURIComponent(x.dataset.object)))) }
  function showContext() { document.getElementById('formContent').innerHTML = '<h2>连接与用户上下文</h2><form id="contextForm"><div class="field"><label>API 地址</label><input name="baseUrl" value="' + esc(Api.context.baseUrl) + '" required></div><div class="field"><label>当前用户 ID</label><input name="userId" type="number" min="1" value="' + Api.context.userId + '" required></div><br><button class="button primary">保存并刷新</button></form>'; formDialog.showModal(); document.getElementById('contextForm').onsubmit = e => { e.preventDefault(); const f = new FormData(e.target); Api.saveContext(f.get('baseUrl'), f.get('userId')); formDialog.close(); state.inventory = null; render() } }
  async function render() { setHeader(); content.innerHTML = '<div class="loading">正在读取真实业务数据…</div>'; try { const fn = { dashboard: renderDashboard, questions: renderQuestions, collection: renderCollection, knowledge: renderKnowledge, readings: renderReadings, plan: renderPlan, records: renderRecords, abilities: renderAbilities, problems: renderProblems, diagnoses: renderDiagnoses, 'mock-papers': renderMockPapers, 'mock-records': renderMockRecords, 'mock-analysis': renderMockAnalysis, ai: renderAi, sources: renderSources, system: renderSystem }[state.view]; await fn(); bindObjects(); const retry = content.querySelector('[data-retry]'); if (retry) retry.onclick = render } catch (error) { if (!content.querySelector('.error-state')) content.innerHTML = '<div class="error-state">页面加载失败：' + esc(error.message) + '<br><button class="button small" data-retry>重试</button></div>'; const retry = content.querySelector('[data-retry]'); if (retry) retry.onclick = render } }

  buildNavigation(); document.querySelectorAll('dialog .dialog-close').forEach(x => x.onclick = () => x.closest('dialog').close()); document.getElementById('contextButton').onclick = showContext
  const initial = location.hash.replace('#', '').split(':'); state.view = pages[initial[0]] ? initial[0] : 'dashboard'; state.tab = initial[1] || ''; window.onhashchange = () => { const bits = location.hash.replace('#', '').split(':'); if (bits[0] !== state.view || (bits[1] || '') !== state.tab) { state.view = pages[bits[0]] ? bits[0] : 'dashboard'; state.tab = bits[1] || ''; render() } }; render()
})()
