package com.gkstudy.mockexam.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.gkstudy.ability.mapper.AbilityMapper;
import com.gkstudy.common.BusinessException;
import com.gkstudy.essay.dto.EssayEvaluationResult;
import com.gkstudy.essay.engine.EssayGrader;
import com.gkstudy.essay.mapper.EssayQuestionMapper;
import com.gkstudy.essay.model.EssayQuestion;
import com.gkstudy.learningproblem.mapper.LearningProblemMapper;
import com.gkstudy.learningproblem.model.LearningProblem;
import com.gkstudy.mockexam.dto.MockAnswerRequest;
import com.gkstudy.mockexam.dto.MockSessionView;
import com.gkstudy.mockexam.engine.MockCalibrationEngine;
import com.gkstudy.mockexam.engine.MockCalibrationEngine.Calibration;
import com.gkstudy.mockexam.engine.MockCalibrationEngine.SectionStat;
import com.gkstudy.mockexam.mapper.MockExamMapper;
import com.gkstudy.mockexam.model.*;
import com.gkstudy.question.mapper.QuestionMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.*;
import java.util.*;

@Service
public class MockExamService {
 private static final Set<String> EXAM_PROBLEM_TYPES=new HashSet<>(Arrays.asList("EXAM_TIME_MANAGEMENT","EXAM_COMPLETION","EXAM_SECTION_STABILITY","EXAM_ORDER_STRATEGY","EXAM_PERFORMANCE_GAP"));
 private final MockExamMapper mapper; private final QuestionMapper questionMapper; private final EssayQuestionMapper essayQuestionMapper; private final EssayGrader essayGrader;
 private final AbilityMapper abilityMapper; private final LearningProblemMapper problemMapper; private final MockCalibrationEngine calibrationEngine; private final ObjectMapper json;
 public MockExamService(MockExamMapper mapper,QuestionMapper questionMapper,EssayQuestionMapper essayQuestionMapper,EssayGrader essayGrader,AbilityMapper abilityMapper,LearningProblemMapper problemMapper,MockCalibrationEngine calibrationEngine,ObjectMapper json){this.mapper=mapper;this.questionMapper=questionMapper;this.essayQuestionMapper=essayQuestionMapper;this.essayGrader=essayGrader;this.abilityMapper=abilityMapper;this.problemMapper=problemMapper;this.calibrationEngine=calibrationEngine;this.json=json;}

 public List<MockPaper> papers(){return mapper.listActivePapers();} public List<MockPaper> adminPapers(){return mapper.listAllPapers();}
 public MockPaper paper(Long id){MockPaper p=requiredPaper(id); p.setSections(mapper.findSections(id)); List<MockPaperItem> items=hydrateItems(id); for(MockPaperSection s:p.getSections()){List<MockPaperItem> own=new ArrayList<>();for(MockPaperItem i:items)if(s.getId().equals(i.getSectionId()))own.add(i);s.setItems(own);}return p;}

 @Transactional public MockPaper createPaper(MockPaper paper){
  if(paper.getName()==null||paper.getName().trim().isEmpty()||paper.getDurationMinutes()==null||paper.getDurationMinutes()<=0||paper.getTotalScore()==null)throw new BusinessException("MOCK_PAPER_INVALID","试卷名称、时长和总分不能为空");
  if(!"XINGCE".equals(paper.getExamType())&&!"SHENLUN".equals(paper.getExamType()))throw new BusinessException("MOCK_PAPER_INVALID","考试类型仅支持行测或申论");
  paper.setUsageType("MOCK_RESERVED");paper.setStatus("DRAFT"); mapper.insertPaper(paper); int order=1;
  for(MockPaperSection section:paper.getSections()){section.setPaperId(paper.getId());mapper.insertSection(section);for(MockPaperItem item:section.getItems()){item.setPaperId(paper.getId());item.setSectionId(section.getId());if(item.getSortNo()==null)item.setSortNo(order);order++;mapper.insertItem(item);}}
  return paper(paper.getId());
 }
 @Transactional public MockPaper changeStatus(Long id,String status){requiredPaper(id);if(!Arrays.asList("ACTIVE","SUSPENDED","ARCHIVED").contains(status))throw new BusinessException("MOCK_STATUS_INVALID","不支持的试卷状态");if("ACTIVE".equals(status)&&mapper.countNonReservedQuestions(id)>0)throw new BusinessException("MOCK_QUESTION_NOT_RESERVED","正式模考只能使用模考专用题目");mapper.updatePaperStatus(id,status);return paper(id);}

 @Transactional public MockSessionView start(Long userId,Long paperId){MockPaper p=requiredPaper(paperId);if(!"ACTIVE".equals(p.getStatus()))throw new BusinessException("MOCK_PAPER_UNAVAILABLE","试卷尚未启用");List<MockPaperItem> items=hydrateItems(paperId);if(items.isEmpty())throw new BusinessException("MOCK_PAPER_EMPTY","试卷暂无题目");MockSession s=new MockSession();s.setUserId(userId);s.setPaperId(paperId);s.setStartTime(LocalDateTime.now());s.setStatus("IN_PROGRESS");mapper.insertSession(s);return new MockSessionView(s,p,items,Collections.emptyList(),s.getStartTime().plusMinutes(p.getDurationMinutes()));}
 @Transactional public MockSessionView session(Long userId,Long sessionId){MockSession s=requiredSession(userId,sessionId);MockPaper p=requiredPaper(s.getPaperId());if("IN_PROGRESS".equals(s.getStatus())&&LocalDateTime.now().isAfter(s.getStartTime().plusMinutes(p.getDurationMinutes()))){submitInternal(s,p,"AUTO_TIME_LIMIT");s=requiredSession(userId,sessionId);}return new MockSessionView(s,p,hydrateItems(p.getId()),mapper.findAnswers(s.getId()),s.getStartTime().plusMinutes(p.getDurationMinutes()));}

 @Transactional public MockAnswer answer(Long userId,Long sessionId,MockAnswerRequest request,boolean skip){
  MockSession s=requiredOpenSession(userId,sessionId);MockPaper p=requiredPaper(s.getPaperId());if(LocalDateTime.now().isAfter(s.getStartTime().plusMinutes(p.getDurationMinutes()))){submitInternal(s,p,"AUTO_TIME_LIMIT");throw new BusinessException("MOCK_TIME_UP","考试时间已到，系统已自动交卷");}
  MockPaperItem item=mapper.findItem(request.getPaperItemId());if(item==null||!p.getId().equals(item.getPaperId()))throw new BusinessException("MOCK_ITEM_NOT_FOUND","试题不属于当前试卷");
  MockAnswer a=new MockAnswer();a.setSessionId(sessionId);a.setPaperItemId(item.getId());a.setQuestionId(item.getQuestionId());a.setEssayQuestionId(item.getEssayQuestionId());a.setSectionCode(item.getSectionCode());a.setAnswerOrder(mapper.nextAnswerOrder(sessionId));a.setDurationMs(request.getDurationMs());a.setStartTime(request.getStartedAtEpochMs()==null?LocalDateTime.now().minusNanos(request.getDurationMs()*1000000):LocalDateTime.ofInstant(Instant.ofEpochMilli(request.getStartedAtEpochMs()),ZoneId.systemDefault()));a.setSubmitTime(LocalDateTime.now());
  if(skip){a.setResultStatus("SKIPPED");a.setUserAnswer(null);a.setScore(BigDecimal.ZERO);}else if(request.getUserAnswer()==null||request.getUserAnswer().trim().isEmpty()){throw new BusinessException("MOCK_ANSWER_EMPTY","答案不能为空");}else{a.setUserAnswer(request.getUserAnswer());if("QUESTION".equals(item.getItemType()))gradeObjective(a,item);else{a.setResultStatus("COMPLETED");a.setWordCount(countWords(request.getUserAnswer()));}}
  mapper.upsertAnswer(a);return mapper.findAnswer(sessionId,item.getId());
 }

 @Transactional public MockResult submit(Long userId,Long sessionId){MockSession s=requiredOpenSession(userId,sessionId);return submitInternal(s,requiredPaper(s.getPaperId()),"MANUAL");}
 public MockResult result(Long userId,Long sessionId){requiredSession(userId,sessionId);MockResult r=mapper.findResult(sessionId);if(r==null)throw new BusinessException("MOCK_RESULT_NOT_READY","模考尚未交卷");decorateResult(r);return r;}
 public List<MockSession> history(Long userId){return mapper.findSessionsByUser(userId);} public List<MockResult> performance(Long userId){List<MockResult> rs=mapper.findResultsByUser(userId);for(MockResult r:rs)decorateResult(r);return rs;}

 private MockResult submitInternal(MockSession s,MockPaper p,String submitType){
  MockResult existing=mapper.findResult(s.getId());if(existing!=null){decorateResult(existing);return existing;}
  List<MockPaperItem> items=hydrateItems(p.getId());Map<Long,MockAnswer> answered=new HashMap<>();for(MockAnswer a:mapper.findAnswers(s.getId()))answered.put(a.getPaperItemId(),a);
  for(MockPaperItem item:items)if(!answered.containsKey(item.getId())){MockAnswer a=new MockAnswer();a.setSessionId(s.getId());a.setPaperItemId(item.getId());a.setQuestionId(item.getQuestionId());a.setEssayQuestionId(item.getEssayQuestionId());a.setSectionCode(item.getSectionCode());a.setResultStatus("UNANSWERED");a.setDurationMs(0L);a.setScore(BigDecimal.ZERO);mapper.upsertAnswer(a);}
  List<MockAnswer> answers=mapper.findAnswers(s.getId());gradeEssays(items,answers);answers=mapper.findAnswers(s.getId());List<SectionStat> stats=aggregate(p,items,answers);
  int submittedCount=mapper.countSubmittedSessions(s.getUserId())+1;List<Calibration> calibrations=calibrationEngine.calibrate(stats,abilityMapper.findByUserId(s.getUserId()),submittedCount);
  MockResult r=new MockResult();r.setSessionId(s.getId());r.setTotalScore(sumScore(answers));r.setAccuracyRate(rate(count(answers,"CORRECT"),objectiveCount(items)));r.setCompletionRate(rate(completedCount(answers),items.size()));r.setTotalDurationMs(Math.min(Duration.between(s.getStartTime(),LocalDateTime.now()).toMillis(),p.getDurationMinutes()*60000L));r.setSectionStatsJson(write(stats));r.setCalibrationJson(write(calibrations));mapper.insertResult(r);
  s.setSubmitTime(LocalDateTime.now());s.setDurationMs(r.getTotalDurationMs());s.setStatus("SUBMITTED");s.setTotalScore(r.getTotalScore());s.setCompletionRate(r.getCompletionRate());s.setSubmitType(submitType);mapper.updateSession(s);updateProblems(s,calibrations);decorateResult(r);return r;
 }

 private void gradeObjective(MockAnswer a,MockPaperItem item){a.setCorrectAnswerSnapshot(item.getCorrectAnswer());if(a.getDurationMs()>item.getStandardTimeSeconds()*1500L){a.setResultStatus("TIMEOUT");a.setScore(BigDecimal.ZERO);return;}boolean correct=item.getCorrectAnswer()!=null&&item.getCorrectAnswer().trim().equalsIgnoreCase(a.getUserAnswer().trim());a.setResultStatus(correct?"CORRECT":"WRONG");a.setScore(correct?item.getScore():BigDecimal.ZERO);}
 private void gradeEssays(List<MockPaperItem> items,List<MockAnswer> answers){Map<Long,MockPaperItem> map=new HashMap<>();for(MockPaperItem i:items)map.put(i.getId(),i);for(MockAnswer a:answers){if(a.getEssayQuestionId()==null||a.getUserAnswer()==null||a.getEvaluationJson()!=null)continue;MockPaperItem item=map.get(a.getPaperItemId());EssayQuestion q=essayQuestionMapper.findById(a.getEssayQuestionId());try{EssayEvaluationResult e=essayGrader.grade(q,a.getUserAnswer(),a.getDurationMs());a.setEvaluationJson(write(e));a.setScore(item.getScore().multiply(BigDecimal.valueOf(e.getTotalScore())).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP));a.setResultStatus("COMPLETED");}catch(RuntimeException ex){Map<String,Object> failure=new LinkedHashMap<>();failure.put("status","FAILED");failure.put("message","AI评分暂时不可用，可稍后查看");a.setEvaluationJson(write(failure));a.setScore(BigDecimal.ZERO);}mapper.upsertAnswer(a);}}
 private List<SectionStat> aggregate(MockPaper p,List<MockPaperItem> items,List<MockAnswer> answers){Map<Long,MockPaperItem> itemMap=new HashMap<>();for(MockPaperItem i:items)itemMap.put(i.getId(),i);Map<String,SectionStat> result=new LinkedHashMap<>();Map<String,MockPaperSection> sectionByCode=new HashMap<>();for(MockPaperSection s:mapper.findSections(p.getId()))sectionByCode.put(s.getSectionCode(),s);Map<String,Integer> fragmentation=orderFragmentation(answers);
  for(MockPaperItem i:items){MockPaperSection s=sectionByCode.get(i.getSectionCode());result.computeIfAbsent(i.getSectionCode(),k->new SectionStat(k,i.getSectionName(),s==null?null:s.getKnowledgePointId())).setTotalCount(result.get(i.getSectionCode()).getTotalCount()+1);}
  Map<String,List<MockAnswer>> grouped=new HashMap<>();for(MockAnswer a:answers)grouped.computeIfAbsent(a.getSectionCode(),k->new ArrayList<>()).add(a);
  for(SectionStat stat:result.values()){List<MockAnswer> list=grouped.getOrDefault(stat.getSectionCode(),Collections.emptyList());long duration=0;BigDecimal score=BigDecimal.ZERO;for(MockAnswer a:list){duration+=a.getDurationMs();score=score.add(a.getScore()==null?BigDecimal.ZERO:a.getScore());if("CORRECT".equals(a.getResultStatus()))stat.setCorrectCount(stat.getCorrectCount()+1);else if("WRONG".equals(a.getResultStatus()))stat.setWrongCount(stat.getWrongCount()+1);else if("SKIPPED".equals(a.getResultStatus()))stat.setSkippedCount(stat.getSkippedCount()+1);else if("UNANSWERED".equals(a.getResultStatus()))stat.setUnansweredCount(stat.getUnansweredCount()+1);else if("TIMEOUT".equals(a.getResultStatus()))stat.setTimeoutCount(stat.getTimeoutCount()+1);}stat.setScore(score);int objective=0;for(MockPaperItem i:items)if(stat.getSectionCode().equals(i.getSectionCode())&&"QUESTION".equals(i.getItemType()))objective++;stat.setAccuracyRate(rate(stat.getCorrectCount(),objective));stat.setCompletionRate(rate(stat.getTotalCount()-stat.getUnansweredCount(),stat.getTotalCount()));stat.setAverageDurationMs(list.isEmpty()?0:duration/list.size());stat.setSecondHalfDrop(secondHalfDrop(list));stat.setOrderFragmentation(fragmentation.getOrDefault(stat.getSectionCode(),0));}
  return new ArrayList<>(result.values());}
 /** 按全局作答顺序统计每个模块被穿插成的连续段数：段数越多说明做题顺序越跳跃。 */
 private Map<String,Integer> orderFragmentation(List<MockAnswer> answers){List<MockAnswer> byOrder=new ArrayList<>(answers);byOrder.sort(Comparator.comparing(a->a.getAnswerOrder()==null?Integer.MAX_VALUE:a.getAnswerOrder()));Map<String,Integer> fragments=new HashMap<>();String last=null;for(MockAnswer a:byOrder){String code=a.getSectionCode()==null?"":a.getSectionCode();if(!code.equals(last))fragments.merge(code,1,Integer::sum);last=code;}return fragments;}
 private BigDecimal secondHalfDrop(List<MockAnswer> list){if(list.size()<4)return BigDecimal.ZERO;list.sort(Comparator.comparing(a->a.getAnswerOrder()==null?Integer.MAX_VALUE:a.getAnswerOrder()));int half=list.size()/2;double first=accuracy(list.subList(0,half)),second=accuracy(list.subList(half,list.size()));return decimal(Math.max(0,first-second));}
 private double accuracy(List<MockAnswer> list){if(list.isEmpty())return 0;int c=0;for(MockAnswer a:list)if("CORRECT".equals(a.getResultStatus()))c++;return c*100.0/list.size();}
 private void updateProblems(MockSession session,List<Calibration> calibrations){LocalDateTime now=session.getSubmitTime();for(Calibration c:calibrations){if(c.getKnowledgePointId()==null)continue;if(c.getIssueType()!=null){LearningProblem p=problemMapper.findForUpdate(session.getUserId(),c.getKnowledgePointId(),c.getIssueType());String old=p==null?null:p.getStatus();if(p==null){p=new LearningProblem();p.setUserId(session.getUserId());p.setKnowledgePointId(c.getKnowledgePointId());p.setProblemType(c.getIssueType());p.setDiscoveredTime(now);p.setValidationCount(0);p.setValidationPassCount(0);}p.setStatus(calibrationEngine.nextProblemStatus(old,true));if("REOPENED".equals(p.getStatus()))p.setResolvedTime(null);p.setTitle(c.getSectionName()+problemLabel(c.getIssueType()));p.setDescription(c.getConclusion());p.setSeverity(decimal(Math.min(100,Math.abs(c.getGap().doubleValue())+25)));p.setPriorityScore(p.getSeverity());p.setEvidenceJson(write(c));if(p.getId()==null)problemMapper.insert(p);else problemMapper.update(p);if(!Objects.equals(old,p.getStatus()))problemMapper.insertHistory(p,old,now);}else improveExamProblems(session.getUserId(),c,now);}}
 private void improveExamProblems(Long userId,Calibration c,LocalDateTime now){for(String type:EXAM_PROBLEM_TYPES){LearningProblem p=problemMapper.findForUpdate(userId,c.getKnowledgePointId(),type);if(p==null||"RESOLVED".equals(p.getStatus()))continue;String old=p.getStatus();p.setStatus(calibrationEngine.nextProblemStatus(old,false));if("RESOLVED".equals(p.getStatus()))p.setResolvedTime(now);p.setEvidenceJson(write(c));problemMapper.update(p);if(!old.equals(p.getStatus()))problemMapper.insertHistory(p,old,now);}}
 private String problemLabel(String type){if("EXAM_COMPLETION".equals(type))return "模考完成率问题";if("EXAM_TIME_MANAGEMENT".equals(type))return "时间分配问题";if("EXAM_SECTION_STABILITY".equals(type))return "考试稳定性问题";if("EXAM_ORDER_STRATEGY".equals(type))return "做题顺序问题";if("EXAM_PERFORMANCE_GAP".equals(type))return "考试表现落差";return "知识掌握问题";}
 private List<MockPaperItem> hydrateItems(Long paperId){List<MockPaperItem> items=mapper.findItems(paperId);for(MockPaperItem i:items)if(i.getQuestionId()!=null)i.setOptions(questionMapper.findOptions(i.getQuestionId()));return items;}
 private void decorateResult(MockResult r){try{r.setSectionStats(json.readValue(r.getSectionStatsJson(),new TypeReference<List<Map<String,Object>>>(){}));r.setCalibrations(json.readValue(r.getCalibrationJson(),new TypeReference<List<Map<String,Object>>>(){}));r.setAnswers(mapper.findAnswers(r.getSessionId()));}catch(Exception e){throw new IllegalStateException("模考结果解析失败",e);}}
 private MockPaper requiredPaper(Long id){MockPaper p=mapper.findPaper(id);if(p==null)throw new BusinessException("MOCK_PAPER_NOT_FOUND","模考试卷不存在");return p;} private MockSession requiredSession(Long userId,Long id){MockSession s=mapper.findSession(id);if(s==null||!userId.equals(s.getUserId()))throw new BusinessException("MOCK_SESSION_NOT_FOUND","模考记录不存在");return s;} private MockSession requiredOpenSession(Long userId,Long id){MockSession s=mapper.findSessionForUpdate(id);if(s==null||!userId.equals(s.getUserId()))throw new BusinessException("MOCK_SESSION_NOT_FOUND","模考记录不存在");if(!"IN_PROGRESS".equals(s.getStatus()))throw new BusinessException("MOCK_SESSION_CLOSED","本次模考已交卷");return s;}
 private int countWords(String text){return text==null?0:text.replaceAll("\\s+","").length();} private int count(List<MockAnswer> list,String status){int n=0;for(MockAnswer a:list)if(status.equals(a.getResultStatus()))n++;return n;} private int completedCount(List<MockAnswer> list){int n=0;for(MockAnswer a:list)if(!"UNANSWERED".equals(a.getResultStatus()))n++;return n;} private int objectiveCount(List<MockPaperItem> items){int n=0;for(MockPaperItem i:items)if("QUESTION".equals(i.getItemType()))n++;return n;} private BigDecimal sumScore(List<MockAnswer> list){BigDecimal v=BigDecimal.ZERO;for(MockAnswer a:list)if(a.getScore()!=null)v=v.add(a.getScore());return v.setScale(2,RoundingMode.HALF_UP);} private BigDecimal rate(int a,int b){return decimal(b==0?0:a*100.0/b);} private BigDecimal decimal(double v){return BigDecimal.valueOf(v).setScale(2,RoundingMode.HALF_UP);} private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException("模考数据序列化失败",e);}}
}
