package com.gkstudy.mockexam;
import com.gkstudy.ability.model.AbilityProfile; import com.gkstudy.mockexam.engine.MockCalibrationEngine; import com.gkstudy.mockexam.engine.MockCalibrationEngine.*; import org.junit.jupiter.api.Test; import java.math.BigDecimal; import java.util.*; import static org.junit.jupiter.api.Assertions.*;
class MockCalibrationEngineTest {
 private final MockCalibrationEngine engine=new MockCalibrationEngine();
 @Test void highDailyLowCompletionMeansCompletionNotMastery(){Calibration c=run(78,45,60,0,0);assertEquals("EXAM_COMPLETION",c.getIssueType());assertTrue(c.getConclusion().contains("完成率"));}
 @Test void highDailyLowMockWithTimeoutMeansTimeManagement(){Calibration c=run(78,55,90,3,0);assertEquals("EXAM_TIME_MANAGEMENT",c.getIssueType());assertTrue(c.getConclusion().contains("时间"));}
 @Test void lateAccuracyDropMeansStability(){Calibration c=run(78,55,90,0,25);assertEquals("EXAM_SECTION_STABILITY",c.getIssueType());}
 @Test void fragmentedAnswerOrderMeansOrderStrategy(){Calibration c=run(78,55,90,0,0,4);assertEquals("EXAM_ORDER_STRATEGY",c.getIssueType());assertTrue(c.getConclusion().contains("顺序"));}
 @Test void contiguousAnswerOrderFallsThroughToOtherTypes(){assertEquals("EXAM_PERFORMANCE_GAP",run(78,55,90,0,0,2).getIssueType());assertEquals("EXAM_TIME_MANAGEMENT",run(78,55,90,3,0,1).getIssueType());}
 @Test void unexplainedGapIsPerformanceGap(){assertEquals("EXAM_PERFORMANCE_GAP",run(78,55,90,0,0).getIssueType());}
 @Test void dailyAndMockBothLowMeansKnowledgeWeakness(){assertEquals("MASTERY",run(42,38,90,0,0).getIssueType());}
 @Test void repeatedMocksRaiseCalibrationConfidence(){Calibration first=engine.calibrate(Collections.singletonList(stat(55,90,1,0)),Collections.singletonList(ability(78)),1).get(0);Calibration third=engine.calibrate(Collections.singletonList(stat(55,90,1,0)),Collections.singletonList(ability(78)),3).get(0);assertTrue(third.getConfidence().compareTo(first.getConfidence())>0);}
 @Test void repeatedIssueConfirmsAndImprovementResolves(){String status=engine.nextProblemStatus(null,true);assertEquals("OBSERVING",status);status=engine.nextProblemStatus(status,true);assertEquals("CONFIRMED",status);status=engine.nextProblemStatus(status,false);assertEquals("PROCESSING",status);status=engine.nextProblemStatus(status,false);assertEquals("VERIFYING",status);status=engine.nextProblemStatus(status,false);assertEquals("RESOLVED",status);assertEquals("REOPENED",engine.nextProblemStatus(status,true));}
 private Calibration run(double daily,double mock,double completion,int timeout,double drop){return run(daily,mock,completion,timeout,drop,0);}
 private Calibration run(double daily,double mock,double completion,int timeout,double drop,int fragmentation){return engine.calibrate(Collections.singletonList(stat(mock,completion,timeout,drop,fragmentation)),Collections.singletonList(ability(daily)),1).get(0);} private SectionStat stat(double mock,double completion,int timeout,double drop){return stat(mock,completion,timeout,drop,0);} private SectionStat stat(double mock,double completion,int timeout,double drop,int fragmentation){SectionStat s=new SectionStat("DATA_ANALYSIS","资料分析",10L);s.setTotalCount(10);s.setAccuracyRate(BigDecimal.valueOf(mock));s.setCompletionRate(BigDecimal.valueOf(completion));s.setTimeoutCount(timeout);s.setSecondHalfDrop(BigDecimal.valueOf(drop));s.setOrderFragmentation(fragmentation);return s;} private AbilityProfile ability(double mastery){AbilityProfile a=new AbilityProfile();a.setKnowledgePointId(10L);a.setMasteryScore(BigDecimal.valueOf(mastery));return a;}
}
