package com.gkstudy.mockexam;
import com.fasterxml.jackson.databind.ObjectMapper; import com.gkstudy.ability.mapper.AbilityMapper; import com.gkstudy.ability.model.AbilityProfile; import com.gkstudy.common.BusinessException; import com.gkstudy.essay.engine.EssayGrader; import com.gkstudy.essay.mapper.EssayQuestionMapper; import com.gkstudy.essay.model.EssayQuestion; import com.gkstudy.learningproblem.mapper.LearningProblemMapper; import com.gkstudy.learningproblem.model.LearningProblem; import com.gkstudy.mockexam.dto.*; import com.gkstudy.mockexam.engine.MockCalibrationEngine; import com.gkstudy.mockexam.mapper.MockExamMapper; import com.gkstudy.mockexam.model.*; import com.gkstudy.mockexam.service.MockExamService; import com.gkstudy.question.mapper.QuestionMapper; import org.junit.jupiter.api.*; import org.mockito.ArgumentCaptor; import java.math.BigDecimal; import java.time.LocalDateTime; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
class MockExamServiceTest {
 private MockExamMapper mapper; private QuestionMapper questions; private AbilityMapper abilities; private LearningProblemMapper problems; private EssayQuestionMapper essayQuestions; private EssayGrader grader; private MockExamService service;
 @BeforeEach void setUp(){mapper=mock(MockExamMapper.class);questions=mock(QuestionMapper.class);abilities=mock(AbilityMapper.class);problems=mock(LearningProblemMapper.class);essayQuestions=mock(EssayQuestionMapper.class);grader=mock(EssayGrader.class);service=new MockExamService(mapper,questions,essayQuestions,grader,abilities,problems,new MockCalibrationEngine(),new ObjectMapper().findAndRegisterModules());}
 @Test void mockReservedIsolationRejectsActivation(){when(mapper.findPaper(1L)).thenReturn(paper("DRAFT"));when(mapper.countNonReservedQuestions(1L)).thenReturn(1);BusinessException e=assertThrows(BusinessException.class,()->service.changeStatus(1L,"ACTIVE"));assertEquals("MOCK_QUESTION_NOT_RESERVED",e.getCode());verify(mapper,never()).updatePaperStatus(anyLong(),anyString());}
 @Test void sessionCreationUsesRealPaperTimer(){MockPaper p=paper("ACTIVE");when(mapper.findPaper(1L)).thenReturn(p);when(mapper.findItems(1L)).thenReturn(Collections.singletonList(item(11L,"B",60)));doAnswer(i->{((MockSession)i.getArgument(0)).setId(7L);return 1;}).when(mapper).insertSession(any());MockSessionView view=service.start(9L,1L);assertEquals(7L,view.getSession().getId());assertEquals(9L,view.getSession().getUserId());assertEquals(view.getSession().getStartTime().plusMinutes(120),view.getDeadline());}
 @Test void correctAnswerStoresDurationOrderAndSnapshot(){prepareOpen();when(mapper.nextAnswerOrder(7L)).thenReturn(3);MockAnswer saved=new MockAnswer();saved.setResultStatus("CORRECT");when(mapper.findAnswer(7L,11L)).thenReturn(saved);service.answer(9L,7L,request("B",50000),false);ArgumentCaptor<MockAnswer> c=ArgumentCaptor.forClass(MockAnswer.class);verify(mapper).upsertAnswer(c.capture());assertEquals("CORRECT",c.getValue().getResultStatus());assertEquals("B",c.getValue().getCorrectAnswerSnapshot());assertEquals(50000L,c.getValue().getDurationMs());assertEquals(3,c.getValue().getAnswerOrder());}
 @Test void wrongAnswerIsRecorded(){prepareOpen();when(mapper.findAnswer(anyLong(),anyLong())).thenReturn(new MockAnswer());service.answer(9L,7L,request("A",50000),false);ArgumentCaptor<MockAnswer> c=ArgumentCaptor.forClass(MockAnswer.class);verify(mapper).upsertAnswer(c.capture());assertEquals("WRONG",c.getValue().getResultStatus());}
 @Test void skippedIsDifferentFromUnanswered(){prepareOpen();when(mapper.findAnswer(anyLong(),anyLong())).thenReturn(new MockAnswer());service.answer(9L,7L,request(null,10000),true);ArgumentCaptor<MockAnswer> c=ArgumentCaptor.forClass(MockAnswer.class);verify(mapper).upsertAnswer(c.capture());assertEquals("SKIPPED",c.getValue().getResultStatus());assertNull(c.getValue().getUserAnswer());}
 @Test void perQuestionOvertimeIsTimeout(){prepareOpen();when(mapper.findAnswer(anyLong(),anyLong())).thenReturn(new MockAnswer());service.answer(9L,7L,request("B",91000),false);ArgumentCaptor<MockAnswer> c=ArgumentCaptor.forClass(MockAnswer.class);verify(mapper).upsertAnswer(c.capture());assertEquals("TIMEOUT",c.getValue().getResultStatus());assertEquals(0,c.getValue().getScore().compareTo(BigDecimal.ZERO));}
 @Test void manualSubmitFillsUnansweredAndAggregates(){MockSession s=session();MockPaper p=paper("ACTIVE");MockPaperItem i1=item(11L,"B",60),i2=item(12L,"A",60);when(mapper.findSessionForUpdate(7L)).thenReturn(s);when(mapper.findPaper(1L)).thenReturn(p);when(mapper.findItems(1L)).thenReturn(Arrays.asList(i1,i2));MockPaperSection section=section();when(mapper.findSections(1L)).thenReturn(Collections.singletonList(section));List<MockAnswer> stored=new ArrayList<>();MockAnswer correct=new MockAnswer();correct.setSessionId(7L);correct.setPaperItemId(11L);correct.setQuestionId(101L);correct.setSectionCode("DATA_ANALYSIS");correct.setResultStatus("CORRECT");correct.setDurationMs(50000L);correct.setScore(BigDecimal.valueOf(10));stored.add(correct);when(mapper.findAnswers(7L)).thenAnswer(x->new ArrayList<>(stored));doAnswer(x->{MockAnswer a=x.getArgument(0);stored.removeIf(old->old.getPaperItemId().equals(a.getPaperItemId()));stored.add(a);return 1;}).when(mapper).upsertAnswer(any());when(abilities.findByUserId(9L)).thenReturn(Collections.emptyList());when(mapper.countSubmittedSessions(9L)).thenReturn(0);doAnswer(x->{((MockResult)x.getArgument(0)).setId(30L);return 1;}).when(mapper).insertResult(any());MockResult result=service.submit(9L,7L);assertEquals(0,result.getTotalScore().compareTo(BigDecimal.TEN));assertEquals(0,result.getCompletionRate().compareTo(BigDecimal.valueOf(50).setScale(2)));assertTrue(stored.stream().anyMatch(a->"UNANSWERED".equals(a.getResultStatus())));verify(mapper).updateSession(argThat(updated->"SUBMITTED".equals(updated.getStatus())&&"MANUAL".equals(updated.getSubmitType())));}
 @Test void closedSessionCannotOverwriteOriginalAnswer(){MockSession s=session();s.setStatus("SUBMITTED");when(mapper.findSessionForUpdate(7L)).thenReturn(s);assertThrows(BusinessException.class,()->service.answer(9L,7L,request("A",1),false));verify(mapper,never()).upsertAnswer(any());}
 @Test void expiredSessionIsAutomaticallySubmitted(){MockSession s=session();s.setStartTime(LocalDateTime.now().minusMinutes(121));when(mapper.findSession(7L)).thenReturn(s);when(mapper.findPaper(1L)).thenReturn(paper("ACTIVE"));when(mapper.findItems(1L)).thenReturn(Collections.emptyList());when(mapper.findAnswers(7L)).thenReturn(Collections.emptyList());when(mapper.findSections(1L)).thenReturn(Collections.emptyList());when(abilities.findByUserId(9L)).thenReturn(Collections.emptyList());MockSessionView view=service.session(9L,7L);assertEquals("SUBMITTED",view.getSession().getStatus());assertEquals("AUTO_TIME_LIMIT",view.getSession().getSubmitType());verify(mapper).insertResult(any());verify(mapper).updateSession(s);}
 @Test void essayAnswerRecordsCompletionWordCountAndOriginal(){prepareOpenWithEssay();when(mapper.findAnswer(anyLong(),anyLong())).thenReturn(new MockAnswer());service.answer(9L,7L,request("基层治理要点归纳整理",600000),false);ArgumentCaptor<MockAnswer> c=ArgumentCaptor.forClass(MockAnswer.class);verify(mapper).upsertAnswer(c.capture());assertEquals("COMPLETED",c.getValue().getResultStatus());assertEquals(10,c.getValue().getWordCount().intValue());assertEquals("基层治理要点归纳整理",c.getValue().getUserAnswer());}
 @Test void essayGradingSuccessScalesItemScore(){prepareSubmitWithEssay();when(essayQuestions.findById(901L)).thenReturn(new EssayQuestion());when(grader.grade(any(),anyString(),anyLong())).thenReturn(essayResult(80));MockResult result=service.submit(9L,7L);assertEquals(0,result.getTotalScore().compareTo(BigDecimal.valueOf(12).setScale(2)));ArgumentCaptor<MockAnswer> c=ArgumentCaptor.forClass(MockAnswer.class);verify(mapper,atLeastOnce()).upsertAnswer(c.capture());MockAnswer graded=c.getAllValues().get(c.getAllValues().size()-1);assertTrue(graded.getEvaluationJson().contains("LOCAL_RULE_V1"));assertEquals("基层治理要点归纳整理",graded.getUserAnswer());}
 @Test void essayGradingFailureDegradesWithoutBlockingSubmit(){prepareSubmitWithEssay();when(essayQuestions.findById(901L)).thenReturn(new EssayQuestion());when(grader.grade(any(),anyString(),anyLong())).thenThrow(new RuntimeException("AI 不可用"));MockResult result=service.submit(9L,7L);assertNotNull(result);assertEquals(0,result.getTotalScore().compareTo(BigDecimal.ZERO));ArgumentCaptor<MockAnswer> c=ArgumentCaptor.forClass(MockAnswer.class);verify(mapper,atLeastOnce()).upsertAnswer(c.capture());MockAnswer degraded=c.getAllValues().get(c.getAllValues().size()-1);assertTrue(degraded.getEvaluationJson().contains("FAILED"));assertEquals("基层治理要点归纳整理",degraded.getUserAnswer());verify(mapper).updateSession(argThat(s->"SUBMITTED".equals(s.getStatus())));}
 @Test void mockDoesNotOverwriteAbilityProfiles(){prepareSubmit();when(abilities.findByUserId(9L)).thenReturn(Collections.singletonList(ability(10L,78)));service.submit(9L,7L);verify(abilities,only()).findByUserId(9L);}
 @Test void timeManagementProblemCreatedAfterSubmit(){prepareSubmit();when(abilities.findByUserId(9L)).thenReturn(Collections.singletonList(ability(10L,78)));when(mapper.findAnswers(7L)).thenReturn(Collections.singletonList(timeoutAnswer()));when(mapper.findResult(7L)).thenReturn(null);doAnswer(x->{((MockResult)x.getArgument(0)).setId(30L);return 1;}).when(mapper).insertResult(any());service.submit(9L,7L);ArgumentCaptor<LearningProblem> c=ArgumentCaptor.forClass(LearningProblem.class);verify(problems).insert(c.capture());assertEquals("EXAM_TIME_MANAGEMENT",c.getValue().getProblemType());assertEquals("OBSERVING",c.getValue().getStatus());assertTrue(c.getValue().getTitle().contains("资料分析"));}
 @Test void improvedSecondMockAdvancesProblemTowardResolved(){prepareSubmit();AbilityProfile daily=ability(10L,78);when(abilities.findByUserId(9L)).thenReturn(Collections.singletonList(daily));when(mapper.findAnswers(7L)).thenReturn(Collections.singletonList(correctAnswer()));when(mapper.findResult(7L)).thenReturn(null);doAnswer(x->{((MockResult)x.getArgument(0)).setId(31L);return 1;}).when(mapper).insertResult(any());LearningProblem existing=examProblem("CONFIRMED");when(problems.findForUpdate(9L,10L,"EXAM_TIME_MANAGEMENT")).thenReturn(existing);service.submit(9L,7L);ArgumentCaptor<LearningProblem> c=ArgumentCaptor.forClass(LearningProblem.class);verify(problems).update(c.capture());assertEquals("PROCESSING",c.getValue().getStatus());verify(problems).insertHistory(any(),any(),any());}
 private void prepareOpen(){when(mapper.findSessionForUpdate(7L)).thenReturn(session());when(mapper.findPaper(1L)).thenReturn(paper("ACTIVE"));when(mapper.findItem(11L)).thenReturn(item(11L,"B",60));}
 private void prepareSubmit(){MockSession s=session();when(mapper.findSessionForUpdate(7L)).thenReturn(s);when(mapper.findPaper(1L)).thenReturn(paper("ACTIVE"));when(mapper.findItems(1L)).thenReturn(Collections.singletonList(item(11L,"B",60)));when(mapper.findSections(1L)).thenReturn(Collections.singletonList(section()));when(mapper.findAnswers(7L)).thenReturn(Collections.emptyList());when(abilities.findByUserId(9L)).thenReturn(Collections.emptyList());when(mapper.countSubmittedSessions(9L)).thenReturn(0);when(mapper.findResult(7L)).thenReturn(null);doAnswer(x->{((MockResult)x.getArgument(0)).setId(30L);return 1;}).when(mapper).insertResult(any());}
 private void prepareOpenWithEssay(){when(mapper.findSessionForUpdate(7L)).thenReturn(session());when(mapper.findPaper(1L)).thenReturn(paper("ACTIVE"));when(mapper.findItem(11L)).thenReturn(essayItem(11L));}
 private void prepareSubmitWithEssay(){MockSession s=session();when(mapper.findSessionForUpdate(7L)).thenReturn(s);when(mapper.findPaper(1L)).thenReturn(paper("ACTIVE"));when(mapper.findItems(1L)).thenReturn(Collections.singletonList(essayItem(11L)));when(mapper.findSections(1L)).thenReturn(Collections.singletonList(section()));List<MockAnswer> stored=new ArrayList<>();MockAnswer a=new MockAnswer();a.setSessionId(7L);a.setPaperItemId(11L);a.setEssayQuestionId(901L);a.setSectionCode("DATA_ANALYSIS");a.setResultStatus("COMPLETED");a.setUserAnswer("基层治理要点归纳整理");a.setDurationMs(600000L);a.setScore(BigDecimal.ZERO);a.setAnswerOrder(1);stored.add(a);when(mapper.findAnswers(7L)).thenAnswer(x->new ArrayList<>(stored));doAnswer(x->{MockAnswer u=x.getArgument(0);stored.removeIf(old->old.getPaperItemId().equals(u.getPaperItemId()));stored.add(u);return 1;}).when(mapper).upsertAnswer(any());when(abilities.findByUserId(9L)).thenReturn(Collections.emptyList());when(mapper.countSubmittedSessions(9L)).thenReturn(0);when(mapper.findResult(7L)).thenReturn(null);doAnswer(x->{((MockResult)x.getArgument(0)).setId(30L);return 1;}).when(mapper).insertResult(any());}
 private MockPaperItem essayItem(Long id){MockPaperItem i=new MockPaperItem();i.setId(id);i.setPaperId(1L);i.setSectionId(2L);i.setItemType("ESSAY");i.setEssayQuestionId(901L);i.setSectionCode("DATA_ANALYSIS");i.setSectionName("资料分析");i.setScore(BigDecimal.valueOf(15));i.setStandardTimeSeconds(1200);return i;}
 private MockAnswer timeoutAnswer(){MockAnswer a=new MockAnswer();a.setSessionId(7L);a.setPaperItemId(11L);a.setQuestionId(101L);a.setSectionCode("DATA_ANALYSIS");a.setResultStatus("TIMEOUT");a.setDurationMs(91000L);a.setAnswerOrder(1);a.setScore(BigDecimal.ZERO);return a;}
 private MockAnswer correctAnswer(){MockAnswer a=new MockAnswer();a.setSessionId(7L);a.setPaperItemId(11L);a.setQuestionId(101L);a.setSectionCode("DATA_ANALYSIS");a.setResultStatus("CORRECT");a.setDurationMs(50000L);a.setAnswerOrder(1);a.setScore(BigDecimal.TEN);return a;}
 private AbilityProfile ability(Long kp,double mastery){AbilityProfile a=new AbilityProfile();a.setKnowledgePointId(kp);a.setMasteryScore(BigDecimal.valueOf(mastery));return a;}
 private LearningProblem examProblem(String status){LearningProblem p=new LearningProblem();p.setId(50L);p.setUserId(9L);p.setKnowledgePointId(10L);p.setProblemType("EXAM_TIME_MANAGEMENT");p.setStatus(status);return p;}
 private com.gkstudy.essay.dto.EssayEvaluationResult essayResult(double score){return new com.gkstudy.essay.dto.EssayEvaluationResult("LOCAL_RULE_V1",score,new HashMap<>(),new ArrayList<>(),new ArrayList<>(),new ArrayList<>(),new ArrayList<>(),new HashMap<>());}
 private MockPaper paper(String status){MockPaper p=new MockPaper();p.setId(1L);p.setName("行测全真模拟卷");p.setExamType("XINGCE");p.setDurationMinutes(120);p.setTotalScore(BigDecimal.valueOf(100));p.setStatus(status);return p;} private MockSession session(){MockSession s=new MockSession();s.setId(7L);s.setUserId(9L);s.setPaperId(1L);s.setStartTime(LocalDateTime.now().minusMinutes(5));s.setStatus("IN_PROGRESS");return s;} private MockPaperSection section(){MockPaperSection s=new MockPaperSection();s.setId(2L);s.setPaperId(1L);s.setSectionCode("DATA_ANALYSIS");s.setName("资料分析");s.setKnowledgePointId(10L);return s;} private MockPaperItem item(Long id,String answer,int seconds){MockPaperItem i=new MockPaperItem();i.setId(id);i.setPaperId(1L);i.setSectionId(2L);i.setItemType("QUESTION");i.setQuestionId(id+90);i.setSectionCode("DATA_ANALYSIS");i.setSectionName("资料分析");i.setScore(BigDecimal.TEN);i.setCorrectAnswer(answer);i.setStandardTimeSeconds(seconds);return i;} private MockAnswerRequest request(String answer,long duration){MockAnswerRequest r=new MockAnswerRequest();r.setPaperItemId(11L);r.setUserAnswer(answer);r.setDurationMs(duration);return r;}
}
